### ISSUE TITLE
how to run mh after install

### ISSUE THREAD

**Issue by jagarop** [blacha/diablo2#143]
Hello, first of all thanks for this release!

I'm using Windows 10 x64 and I would like to know how to run the maphack after the install is done with node.js/yarn.

**Comment by blacha** [comment]
Howdy!

This repo is very much still a work in progress, The d2:r memory reader/map generator currently constantly crashes and needs a fair bit of setup to get working. 

This codebase will currently only run under linux and will not run on windows computers. The memory reader part is currently using linux's `/proc/$PID/mem`  as a method of reading the memory of another process which doesnt exist in windows.
