### ISSUE TITLE
I got these errors

### ISSUE THREAD

**Issue by cocono1** [blacha/diablo2#147]
{"level":20, "time":1633098330176, "source":"map/d2_client.c:145", "msg":"Initalizing", "path":"game"}
{"level":10, "time":1633098330177, "source":"map/d2_version.h:39", "msg":"CheckGamePath", "exists":"false", "game":"game/Path of Diablo/game.exe"}
{"level":10, "time":1633098330179, "source":"map/d2_version.h:39", "msg":"CheckGamePath", "exists":"false", "game":"game/ProjectD2/game.exe"}
{"level":50, "time":1633098330180, "source":"map/d2_client.c:149", "msg":"Failed to determine game version", "path":"game"}

Did I enter the path incorrectly?
What should I do?

**Comment by blacha** [comment]
The current build of the map generator only works with Path of Diablo or Project Diablo 2


So I have a folder `DiabloII` inside is a `ProjectD2` folder I use `--volume DiabloII:/app/game` which gives my docker container the `game.exe` at:

```bash
/app/game/game.exe # Raw Diablo2

/app/game/ProjectD2/game.exe # PD2 game
```

The map generator will currently only use the PD2 `game.exe`

I have a local branch where I'm working on getting a  d2 classic v1.14b map builder going, but its currently completely broken.
