### ISSUE TITLE
How did you get D2R to work with the map package?

### ISSUE THREAD

**Issue by EternalNooblet** [blacha/diablo2#148]
I built the packages and can start the docker. It complains about `Failed to determine game version`. There is no `game.exe` in d2r, it has `D2R.exe`. Renaming that to game.exe did not help. Since you posted a screenshot with d2r and the map package running, I just wanted to ask how to get that working. Thank you.

**Comment by blacha** [comment]
D2R uses the same map generation logic as D2 classic, the map library generates maps from map seeds using a d2 classic client.

The map generation library right now only works with Path of Diablo or Project Diablo2. I ahve a branch for getting to to work with d2 v1.14b but its currently broken.

The memory reader [@diablo2/memory](https://github.com/blacha/diablo2/tree/master/packages/memory) then can extract a map seed from D2R and use that to generate the map

**Comment by EternalNooblet** [comment]
Do you have an example of how to use @diablo2/memory? There is a readme, but it doesn't show how to initialize the module.

**Comment by blacha** [comment]
`@diablo2/memory` doesnt currently work under windows, in Linux you can read another process's memory by reading `/proc/$PID/mem` I do not have a windows computer to test on so I'm unsure when windows support will be added.

**Comment by EternalNooblet** [comment]
Thank you for providing the info. When I try d2r under wine, all I get is a black screen. How are you running it in Linux?

**Comment by Jagermeister56** [comment]
> Thank you for providing the info. When I try d2r under wine, all I get is a black screen. How are you running it in Linux?

Are you running in a VM or physical computer?

**Comment by blacha** [comment]
I game completely under Linux (Ubuntu 21.04)

D2R runs really well under wine, It does need to have the latest DXVK drivers installed.

**Comment by EternalNooblet** [comment]
I got the memory package to work. Running Fedora 34 natively, I installed bnet using Lutris by following these directions https://github.com/HansKristian-Work/vkd3d-proton/issues/625#issuecomment-903232311. Thank you, @blacha, running on windows lets me read /proc memory. Out of the box master from this repo just works w/o any hardcoding changes.

This is from my offline char named **wtf**: map={ id=1234339171 act=0 difficulty=1 isHardcore=false }

```
[2021-10-04T02:39:22.938Z] WARN Player:NotFound id=01fh4jprcwanf4b2nrkaf6qaff playerName=wtf
[2021-10-04T02:39:22.941Z] INFO Session:WaitForPlayer id=01fh4jprcwanf4b2nrkaf6qaff
[2021-10-04T02:39:23.759Z] DEBUG Player:Offset id=01fh4jprcwanf4b2nrkaf6qaff offset=0x7fffd4ae35dc
[2021-10-04T02:39:28.749Z] DEBUG Player:Offset id=01fh4jprcwanf4b2nrkaf6qaff offset=0x7fffd4ae3ee0
{
  type: 0,
  txtFileNo: 1,
  unitId: 1,
  mode: 5,
  pPlayer: { offset: 0x7fffd4ae3ee0, valid: true },
  actId: 0,
  unk1: 0,
  pAct: { offset: 0x7fffd4ae69c0, valid: true },
  seedA: 2545819388,
  seedB: 666,
  unk2: [ { offset: 0x97be1efc, valid: true } ],
  pPath: { offset: 0x233646b0, valid: true },
  unk3: undefined,
  unk4: [
    { offset: 0x50, valid: false },
    { offset: 0x7fffd4006258, valid: true },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false }
  ],
  pStats: { offset: 0x7ffff63b0010, valid: true },
  unk5: [
    { offset: 0x7fffd4ae3e30, valid: true },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x1d52a390, valid: true },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x1fed31a0, valid: true },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0xe00000000, valid: true },
    { offset: 0x6000002, valid: true },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false },
    { offset: 0x7fffd4aad820, valid: true },
    { offset: 0x00, valid: false },
    { offset: 0x00, valid: false }
  ]
}
[2021-10-04T02:39:30.554Z] INFO Player:Offset:Pointer id=01fh4jprcwanf4b2nrkaf6qaff offset=0x7fffd4ae3ee0 unit=0x2bf7df00 pointers=4
[2021-10-04T02:39:30.554Z] INFO Player:Offset:Pointer:Found id=01fh4jprcwanf4b2nrkaf6qaff offset=0x7fffd4ae3ee0 unit=0x2bf7df00
[2021-10-04T02:39:30.556Z] INFO MapSeed:Changed id=01fh4jprcwanf4b2nrkaf6qaff map={ id=1234339171 act=0 difficulty=1 isHardcore=false }
```

**Comment by blacha** [comment]
Thats cool to see you managed to get it working, The code base is still super rough and will crash alot! but given that seed you should be able to generate the map with `@diablo2/map`

**Comment by EternalNooblet** [comment]
> 
> 
> Thats cool to see you managed to get it working, The code base is still super rough and will crash alot! but given that seed you should be able to generate the map with `@diablo2/map`

Thank you for posting this code! Yes, it takes a few attempts and does not always work. @blacha The `@diablo2/map` package doesnt work on plain d2, but if I installed either POD or PD2, then would it be able to generate a map from any seed? Or would a POD game base only generate maps for POD seeds, and PD2 for PD2?

**Comment by blacha** [comment]
Pd2 and pod seeds are almost 100% exactly the same as d2  but they have more regions


I believe the only zone that doesn't work properly with a pd2 seed is sewers level 2


You can test it with https://diablo2.chard.dev and put your map seed in and have a look around

**Comment by EternalNooblet** [comment]
Oh, i think the seed is actually this: `pPath: { offset: 0x233646b0, valid: true }`, not the map.id like I originally thought. Testing it again on a fresh map now to see. Need to grab a new seed too.

**Comment by blacha** [comment]
Hmm, that is the pointer to the `Path` object where the player location (x/y) is

The map seed is part of `Act` object referenced via the `pAct` var it is also logged as part of the `map=` section in 

```
map={ id=1234339171 act=0 difficulty=1 isHardcore=false }
```

**Comment by EternalNooblet** [comment]
I dumped a new char and have the following `map={ id=906454380 act=0 difficulty=1 isHardcore=false }`. The website doesnt work in FF, I have to use Edge to get a white on gray map for now. Do I have to convert the id from decimal to hex, so that this would be the seed in the link below? 

https://diablo2.chard.dev/?seed=0x3607656c&act=ActI&difficulty=Normal

![image](https://user-images.githubusercontent.com/67196335/135947162-71b4dd32-79b2-4fee-9f0e-dc114043c647.png)

**Comment by blacha** [comment]
> clip of revealing the map for the 1st time: https://streamable.com/e/oe7mto

Awesome!

How did you get it to overlay the map on top of the game window like that?

Also if you follow the `pStats` pointer you will have X/Y coords for the player so you can add a point to the map.

**Comment by wiardvanrij** [comment]
This is quite new for me, but I'm willing to invest some time to make this all work for Windows. If you got any pointers (non-memory xD) to share to help this, let me know

**Comment by EternalNooblet** [comment]
I dont wanna keep this issue open. It's been super helpful and there is still much to figure out. I have had a lot of success running the memory package, gave up on the map for now. Got my own quick setup using plain d2mapapi working in the meantime. Probably next lvl for this stuff is just a standalone generator in something. No d2 of any kind needed. My docker is now 3gb because of that d2mapapi.
