### ISSUE TITLE
d2-map.exe missing

### ISSUE THREAD

**Issue by mgalos999** [blacha/diablo2#152]
In order to generate maps, it seems it relies on a `d2-map.exe` executable.
I can't find any link or mention of where this executable might be located.

https://github.com/blacha/diablo2/blob/5211f0a90c6914963d48f6d9d3dc182e6beebe1e/packages/map/src/map/map.process.ts#L9

**Comment by EternalNooblet** [comment]
I think the intended way to run that is using Docker. The 1st 3 commands are on your host machine to build and start docker. After that you should be inside the running docker container, and run the last command there.
https://github.com/blacha/diablo2/tree/master/packages/map#building

**Comment by mgalos999** [comment]
I see, the executable gets generated by `build.mapgen.sh` when building the docker file.
