### ISSUE TITLE
how to run memory package

### ISSUE THREAD

**Issue by paragcalc** [blacha/diablo2#161]
![scrtest](https://user-images.githubusercontent.com/92309829/136786037-c0e858c9-ad5a-42c4-887f-9b634b99ceb5.png)

I built the package with yarn.
and followed
github.com/blacha/diablo2/issues/148

typed node cli.js
seems working

but with player name 
node cli.js wtf
seems failing

**Comment by blacha** [comment]
The memory package is super unstable it may or may not find your character at all :(
