### ISSUE TITLE
Status 500 Failed to run

### ISSUE THREAD

**Issue by Barakial** [blacha/diablo2#162]
Hello everyone, I launched docker and when I refresh the page in the browser, I see an error in the console
{"level":50,"time":1633962846393,"pid":1,"hostname":"558ecdf57c6a","id":"01fhqwc17m350zbt7v3674781e","id":"01FHQWCGD5A3GYSYSXFHPCEVTK","msg":"Failed to run"}
{"level":30,"time":1633962846395,"pid":1,"hostname":"558ecdf57c6a","id":"01fhqwc17m350zbt7v3674781e","id":"01FHQWCGD5A3GYSYSXFHPCEVTK","duration":10006,"status":500,"msg":"/v1/map/16711935/Normal.json"}

There is nothing on the page
https://i.postimg.cc/DycjhNs0/screenshot-9.png

**Comment by blacha** [comment]
Looks like its hitting the 10 second timeout, running docker under windows is horrible performance unfortunately, I have bumped the timeout to 30 seconds.

for a rough scale my desktop generates these maps in ~1.9 seconds under Ubuntu.

**Comment by blacha** [comment]
Still looks like the 10 second timeout is being hit.

are you sure your running the latest copy of all the code? it should print out something like `v0.6.0`  when it starts
