### ISSUE TITLE
Init:Failed:UnknownGameVersion with D2R

### ISSUE THREAD

**Issue by s1228** [blacha/diablo2#183]
When ever I try to run this with D2R, i just get "Init:Failed:UnknownGameVersion" and it says "MapProcess:Closed" 

Do i need to modify anything, to get this to run with D2R?

**Comment by blacha** [comment]
This does not work with d2r at all, it only works with diablo2 v1.13c or diablo2 v1.14 & Project Diablo2

**Comment by s1228** [comment]
hm, ok. the screenshot of D2R in the readme gave me the impression that it would. thanks for clarifying.

**Comment by blacha** [comment]
The map generation for diablo2 classic and d2r is exactly the same, if you can acquire the seed from your d2r client you can generate the maps for it.

**Comment by arithxp** [comment]
> 
> 
> The map generation for diablo2 classic and d2r is exactly the same, if you can acquire the seed from your d2r client you can generate the maps for it.

Can you share the offset or pattern?
I'm using Windows, so I'd like to know how to read it with a program like Cheat Engine.

**Comment by blacha** [comment]
Something like misterokaygo/D2RAssist would show you how to find the offsets
