### ISSUE TITLE
Nihlathak does not show up as npc object in the level data

### ISSUE THREAD

**Issue by emko** [blacha/diablo2#216]
in the map data, Nihlathak is not here, i tried to look at the code can't seem to figure it out, i assume npc_is_useless is returning true but not sure how this works.

**Comment by blacha** [comment]
I took out the `npc_is_useless` check to see what would happen, But I'm still only getting 1 NPC for Halls of Vaught, NPC code `802` which is too high for the NPC code table.


```
wine bin/d2-map.exe /app/game --seed 16711935 -d 0 -m 124
```

I wonder if the developers have hard coded his spawning logic into the game client somehow.

**Comment by emko** [comment]
yea that 803 is not correct it goes to a location no where near Nihlathak.

tried to get some info, all i can find is 

https://raw.githubusercontent.com/kolton/d2bot-with-kolbot/0ba87a25ef5e9432920e20d93082b936b318e148/d2bs/kolbot/sdk/SuperUniques.txt

**Comment by blacha** [comment]
The game joins together multiple arrays to make new ids. 

with monsters, its all regular monsters then super unique, so having a super unique id of 61 means your actual id is around 790.

The game also has a bunch of hard coded logic which adds things to these lists. For instance the super chests in LK don't exist inside of the object game files at all but is hard coded into the source code eg https://github.com/ThePhrozenKeep/D2MOO/blob/b0951d44f4ef69de8170c3eddae4f6c18fa14086/source/D2Common/src/Drlg/DrlgPreset.cpp#L766

As to where Nihlathak is, his monster id is not shown anywhere on that level as far as I can tell.
