### ISSUE TITLE
How to run the memory scanner

### ISSUE THREAD

**Issue by SilasMueller** [blacha/diablo2#225]
Is the memory scanner able to run on windows machines?

**Comment by blacha** [comment]
No, the scanner currently uses `/proc/$PID/maps` which is a linux only way of reading memory

**Comment by SilasMueller** [comment]
Okay, thanks for the info. Do these Structs and offsets work with the current Version of D2R? 
https://github.com/blacha/diablo2/blob/master/packages/memory/src/struts/d2r.ts

**Comment by blacha** [comment]
These data structures are still all valid, but there are no offsets in this repo. 

Most of the logic is using memory scanning to find patterns in the memory which are then used to find game objects
