### ISSUE TITLE
Build instruction for map is missing log.c

### ISSUE THREAD

**Issue by Toneyisnow** [blacha/diablo2#257]
In the description of map building, there is:
```
RUN i686-w64-mingw32-g++ -o bin/d2-map.exe \
    -Wno-write-strings \
    -static-libgcc -static-libstdc++ \
    map/json.c map/map.c map/offset.c map/d2_client.c map/main.c 
```

And it should be:

```
RUN i686-w64-mingw32-g++ -o bin/d2-map.exe \
    -Wno-write-strings \
    -static-libgcc -static-libstdc++ \
    map/json.c map/map.c map/offset.c map/d2_client.c map/main.c map/log.c
```

The command is missing "map/log.c".

**Comment by blacha** [comment]
Sorry for my super slow response, must have missed this somehow..

That README  was mostly to work around a permission problem with windows, I #275 might be a better solution for the problem rather than duplicating the build command into the README.

**Comment by Toneyisnow** [comment]
Thanks for the response! I also hope there would be better way to fix windows permission issue.

**Comment by blacha** [comment]
I don't have a windows computer so testing under windows is a little patchy, I should setup some more windows/mac pipelines to make sure this actually fixes the problem.
