### ISSUE TITLE
maps image endpoint fails for anything other than act 1

### ISSUE THREAD

**Issue by Tomhoogstra** [blacha/diablo2#295]
Attempting to fetch an image of a map with a level ID higher than 38 returns "Invalid Level"

e.g. 

http://localhost:8899/v1/map/1298509907/0/39.png

http://localhost:8899/v1/map/1298509907/0/130.png

^ literally any id outside of act 1

Act 1 works perfectly other than image text being a little dodgy with the smaller regions (font too big)

Getting the json for ActV shows id 130 is there:

![image](https://user-images.githubusercontent.com/5389944/155354365-b1e0582f-1d13-48e9-bb25-6459a1528114.png)

**Comment by Tomhoogstra** [comment]
This seems to be due to the function returning an array of levels equal to the size of the specific act, but you cannot specify an act in this particular endpoint. Even though it determines the act by the id provided, you cant specify for example you want level 20 from act 5, because when you put level 20 in, it will think you are referring to act 1

**Comment by Tomhoogstra** [comment]
Changing map.image.ts to pass an act ID of -1 fixes the issue

**Comment by blacha** [comment]
Thanks for reporting this and also the investigation! I can reproduce it locally and #297 fixes it for me.
