### ISSUE TITLE
It will not render levels for act 2-5 with this url /v1/map/:seed/:difficulty/:level.png

### ISSUE THREAD

**Issue by mpsOxygen** [blacha/diablo2#400]
It work until Moo Moo Farm (level = 38), and after that just says Invalid Level.

{"level":30,"time":1668695444739,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ2ZZK83VW8XVXTYK527QZSG","duration":0,"status":422,"msg":"/v1/map/0x3617656c/Hell/75.png"}
{"level":40,"time":1668695458418,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ3000KJG8HDQQ8GYN6D1R5M","msg":"Invalid level"}
{"level":30,"time":1668695458419,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ3000KJG8HDQQ8GYN6D1R5M","duration":1,"status":422,"msg":"/v1/map/0x3617656c/Hell/76.png"}
{"level":40,"time":1668695462216,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ3004A735NM2EX3WR3PGPNE","msg":"Invalid level"}
{"level":30,"time":1668695462216,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ3004A735NM2EX3WR3PGPNE","duration":1,"status":422,"msg":"/v1/map/0x3617656c/Hell/77.png"}
{"level":40,"time":1668695466864,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ3008VFSBBM0P17EB0VR0D0","msg":"Invalid level"}
{"level":30,"time":1668695466864,"pid":1,"hostname":"52f62063aeb6","id":"01gj2vwaws88gs8qk9jh37ftzf","id":"01GJ3008VFSBBM0P17EB0VR0D0","duration":0,"status":422,"msg":"/v1/map/0x3617656c/Hell/103.png"}

**Comment by blacha** [comment]
How are you running the map engine? What version of this project are you running?

there was a bug fix a few months ago which should have fixed this issue https://github.com/blacha/diablo2/commit/3247837fb3b3d1fbeeee3197b20a23b166caa38b

**Comment by mpsOxygen** [comment]
Hey, sorry for the late reply. I was using the latest release which had this fix for as far as I know.
