### ISSUE TITLE
map generator build issue

### ISSUE THREAD

**Issue by jinincarnate** [blacha/diablo2#420]
what should be the game path in this step : docker run -it -v "/E/Games/Diablo II":/app/game diablo2/map /bin/bash

as mine is 'C:\Program Files (x86)\Diablo II Resurrected'

**Comment by blacha** [comment]
The map generation was the same between D2R and Diablo2 Classic 1.13c.

This project uses diablo2 LOD 1.13c to generate the maps. https://github.com/blacha/diablo2/tree/master/packages/map#diablo-2
